server:
  port: 8989

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    hostname: localhost




spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://OrderService
        predicates:
        - Path=/order/**
        
      - id: payment-service
        uri: lb://PaymentService
        predicates:
        - Path=/payment/**    
    
